// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: GreeterServer/api/GreeterServer.proto

package api

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GreeterServer service

type GreeterServerService interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...client.CallOption) (*SayHelloResponse, error)
}

type greeterServerService struct {
	c    client.Client
	name string
}

func NewGreeterServerService(name string, c client.Client) GreeterServerService {
	return &greeterServerService{
		c:    c,
		name: name,
	}
}

func (c *greeterServerService) SayHello(ctx context.Context, in *SayHelloRequest, opts ...client.CallOption) (*SayHelloResponse, error) {
	req := c.c.NewRequest(c.name, "GreeterServer.SayHello", in)
	out := new(SayHelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreeterServer service

type GreeterServerHandler interface {
	SayHello(context.Context, *SayHelloRequest, *SayHelloResponse) error
}

func RegisterGreeterServerHandler(s server.Server, hdlr GreeterServerHandler, opts ...server.HandlerOption) error {
	type greeterServer interface {
		SayHello(ctx context.Context, in *SayHelloRequest, out *SayHelloResponse) error
	}
	type GreeterServer struct {
		greeterServer
	}
	h := &greeterServerHandler{hdlr}
	return s.Handle(s.NewHandler(&GreeterServer{h}, opts...))
}

type greeterServerHandler struct {
	GreeterServerHandler
}

func (h *greeterServerHandler) SayHello(ctx context.Context, in *SayHelloRequest, out *SayHelloResponse) error {
	return h.GreeterServerHandler.SayHello(ctx, in, out)
}
